name: 'Ngrok TCP Tunelling'
description: 'A github action for tunelling TCP traffic from within Workflow environemt'

branding:
  icon: 'activity'  
  color: 'green'

inputs:
  timeout:  
    description: 'Challenge deployment timeout'
    required: true
    default: '1h'
  tunnel_type:
    description: 'Type of ngrok tunnel, TCP or http'
    required: true
    default: 'tcp'
  port:
    description: 'The port to forward traffic to'
    required: true
  ngrok_authtoken:
    description: 'Ngrok authorization token'
    required: true

runs:
  using: "composite"
  steps: 
    - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      shell: bash
    - run: unzip -qq ngrok-stable-linux-amd64.zip
      shell: bash
    - run: ./ngrok authtoken ${{ inputs.ngrok_authtoken }}
      shell: bash
    - run: ( timeout ${{ inputs.timeout }} ./ngrok ${{ inputs.tunnel_type }} ${{ inputs.port }} ) &
      shell: bash
